### PR TITLE
Fixes to run startup on Py2 Phoenix 4.0+

### PR DESCRIPTION
**Pull request by Metallicow**
Fixes to run startup on Py2 Phoenix 4.0+

### CODE REVIEW

**Comment by Correct-Syntax** [comment]
@Metallicow, could you clarify what this PR is? If I understand correctly, it's for running Gimel Studio with python 2?

Thank you!

**Comment by Metallicow** [comment]
Yes, these fixes allow Gimel to run with Python2 and wxPy4.0 Phoenix without having deps installed. This makes it easier for dev of the widget from wxpython bare bones side and to check backwards compatibility.
At some point in the future you might want to replace the print statement with raise if there is a dependency problem that needs debugged. 
Also it shows some graphical issues you have with how you did agw aui. The splitters are black for example. and may need a bit more work to get it looking right again theming-wise.

**Comment by Metallicow** [comment]
In python 3 unicode became str, so that's why I changed that line. No need for six.py just for a one-liner.

**Comment by Correct-Syntax** [comment]
> Yes, these fixes allow Gimel to run with Python2 and wxPy4.0 Phoenix without having deps installed. This makes it easier for dev of the widget from wxpython bare bones side and to check backwards compatibility.

That is what I thought. Thank you. Do you think it is still important to support python 2, since its past its end-of-life? Maybe since wxpython does -that's what your thinking?

> At some point in the future you might want to replace the print statement with raise if there is a dependency problem that needs debugged.

Certainly.

> Also it shows some graphical issues you have with how you did agw aui. The splitters are black for example. and may need a bit more work to get it looking right again theming-wise.

O.k. I assume you mean that running Gimel Studio with python 2 causes the splitters to be black?

Thanks again.

**Comment by Metallicow** [comment]
Umm yes support python 2. At least until while wxPython does. I run both because I develop widgets.
At one point python 3 will probably someday make some changes that may be desirable to break from 2. Tho that day will be a long ways off.

No the black is an issue with your coding 99% I'd say. I haven't looked into it yet... just got it to startup. Might be a dc issue you created or a metric you may have set to black.

**Comment by Metallicow** [comment]
Running/developing it in python 2 and python 3 may also a lot of times show me where you have or someone else has made a mistake.
Ex: you may need to use integer division(python change / needs to be //) or maybe a dependency has a bug, etc.. etc..

Overall, there is no reason not to not support cross-compatible code. If at some point the dependencies break python 2, then those features just wont be supported for whatever nodes may use whatever when running in python 2 unless you want to fork your own copy of lib and reimplement py 2 support. The biggest things I usually see that break cross compatible code are usually minimal. Tho annotations will break py2, the py3.8 walrus anywhere in code should be handled with extreme caution.
As far as unicode in python 2/3.4+ you can do `_(u"Translatable string")` if you really are supporting other languages with i18n.

**Pull request merged**
